# Generated by Django 6.1 on 2026-08-20 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text="Defaults to the unit's rent when not supplied.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Derived from the contract period and monthly rent - never set by the client.', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='members.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='units.unit')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ('-start_date', '-id'),
                'indexes': [models.Index(fields=['unit', 'start_date', 'end_date'], name='contract_unit_period_ix')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_date_after_start_date')],
            },
        ),
    ]
